# Generated by Django 5.2.13 on 2026-06-22 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('revenue_today', "Today's Revenue"), ('revenue_this_month', 'Month-to-Date Revenue'), ('profit_today', "Today's Profit"), ('profit_margin', 'Profit Margin %'), ('avg_order_value', 'Average Order Value'), ('cash_flow', 'Cash Flow'), ('inventory_turnover', 'Inventory Turnover'), ('outstanding_receivables', 'Outstanding Receivables')], max_length=30, unique=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('previous_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('trend', models.CharField(choices=[('up', '↑ Up'), ('down', '↓ Down'), ('stable', '→ Stable')], default='stable', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('historical_data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Real-time Metrics',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_type', models.CharField(choices=[('ceo', 'Chief Executive Officer'), ('cfo', 'Chief Financial Officer'), ('coo', 'Chief Operating Officer'), ('cto', 'Chief Technology Officer'), ('cmo', 'Chief Marketing Officer'), ('chairman', 'Chairman'), ('board_member', 'Board Member')], default='ceo', max_length=20)),
                ('executive_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(default='Chief Executive Officer', max_length=100)),
                ('department', models.CharField(default='Executive Office', max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('assistant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assistant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('security_clearance_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10')], default=5)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('email_alerts', models.BooleanField(default=True)),
                ('whatsapp_alerts', models.BooleanField(default=False)),
                ('slack_webhook', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Executive Profiles',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('board', 'Board Meeting'), ('executive', 'Executive Committee'), ('strategy', 'Strategy Session'), ('review', 'Quarterly Review'), ('emergency', 'Emergency Meeting')], max_length=20)),
                ('meeting_date', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('virtual_link', models.URLField(blank=True, null=True)),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True, null=True)),
                ('decisions', models.TextField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to='ceo_module.executiveprofile')),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to='ceo_module.executiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Executive Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_type', models.CharField(choices=[('daily', 'Daily Briefing'), ('weekly', 'Weekly Briefing'), ('monthly', 'Monthly Briefing')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('executive_summary', models.TextField()),
                ('key_metrics', models.JSONField(default=dict)),
                ('achievements', models.TextField()),
                ('challenges', models.TextField()),
                ('upcoming_priorities', models.TextField()),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='briefings/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_briefings', to='ceo_module.executiveprofile')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='ceo_module.executiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Executive Briefings',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view', 'View Data'), ('export', 'Export Report'), ('approve', 'Approval'), ('reject', 'Rejection'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('settings', 'Settings Change')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affected_model', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_id', models.CharField(blank=True, max_length=100, null=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ceo_module.executiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Executive Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('financial', 'Financial Risk'), ('operational', 'Operational Risk'), ('strategic', 'Strategic Risk'), ('compliance', 'Compliance Risk'), ('reputational', 'Reputational Risk'), ('cybersecurity', 'Cybersecurity Risk'), ('market', 'Market Risk')], max_length=20)),
                ('likelihood', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('impact', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('risk_score', models.IntegerField(default=0, editable=False)),
                ('mitigation_strategy', models.TextField()),
                ('mitigation_deadline', models.DateField()),
                ('potential_financial_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mitigation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('analyzing', 'Under Analysis'), ('mitigating', 'Mitigation in Progress'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('accepted', 'Accepted')], default='identified', max_length=20)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical (Immediate Action)'), ('high', 'High (Urgent)'), ('medium', 'Medium (Monitor)'), ('low', 'Low (Acceptable)')], default='low', editable=False, max_length=10)),
                ('identified_date', models.DateTimeField(auto_now_add=True)),
                ('last_review', models.DateTimeField(auto_now=True)),
                ('next_review', models.DateField()),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_risks', to='ceo_module.executiveprofile')),
                ('mitigation_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to='ceo_module.executiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Risk Assessments',
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], max_length=2)),
                ('year', models.IntegerField()),
                ('priority', models.CharField(choices=[('critical', '🔴 Critical'), ('high', '🟠 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('on_track', 'On Track'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_revenue_impact', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estimated_cost_saving', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objectives', to='ceo_module.executiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Strategic Objectives',
                'ordering': ['-year', 'quarter', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('on_track', 'On Track'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('update_notes', models.TextField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='ceo_module.strategicobjective')),
            ],
            options={
                'verbose_name_plural': 'Key Results',
            },
        ),
    ]
