# Generated by Django 5.2 on 2025-04-27 16:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '1.1 Product Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '1.2 Product Category',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Company Logo')),
                ('footer_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer Note (for reports)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2.1 Customer Groups',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': '11. Debts',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=100)),
            ],
            options={
                'verbose_name_plural': '10. Expenses',
            },
        ),
        migrations.CreateModel(
            name='GroupSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(auto_now_add=True)),
                ('total_vendor_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_customer_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': '5. Group Summaries',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '1.4 Product Location',
            },
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('product', 'Product Management'), ('purchase', 'Purchases'), ('sale', 'Sales'), ('warehouse', 'Warehouse Management'), ('report', 'Reporting'), ('backup', 'Backup & Restore'), ('other', 'Other')], max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '📘 Training Topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '1.3 Product Type',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1.5 Product Unit',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Vendor',
            },
        ),
        migrations.CreateModel(
            name='VendorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3.1 Vendor Groups',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set profit margin percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='app.customergroup')),
            ],
            options={
                'verbose_name_plural': '2. Customers',
            },
        ),
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.datetime.now, unique=True)),
                ('locked', models.BooleanField(default=False)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
            ],
            options={
                'verbose_name_plural': '9.0 Monthly Closings',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='app_monthly_month_cba5ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('used', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=10)),
                ('low_stock_threshold', models.FloatField(default=10.0, help_text='Set minimum stock level for alerts.')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.location')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.types')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.unit')),
            ],
            options={
                'verbose_name_plural': '1. Product Name',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=10, null=True)),
                ('waiting_for_bill', models.BooleanField(default=False)),
                ('pur_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_purchase', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app.monthlyclosing')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
            options={
                'verbose_name_plural': '4. Purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase')),
            ],
            options={
                'verbose_name_plural': '4.1. Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRetrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10)),
                ('purchase_return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged Goods'), ('incorrect', 'Incorrect Shipment'), ('expired', 'Expired Stock'), ('other', 'Other')], default='other', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_purchase', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='app.monthlyclosing')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app.purchase')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
            options={
                'verbose_name_plural': '4.3. Purchase Retrn',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRetrnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='app.purchaseretrn')),
            ],
            options={
                'verbose_name_plural': '4.4. Purchase Return Items',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('monthly_sale', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='app.monthlyclosing')),
            ],
            options={
                'verbose_name_plural': '5. Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleRetrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10)),
                ('sale_return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged Goods'), ('incorrect', 'Incorrect Shipment'), ('expired', 'Expired Stock'), ('other', 'Other')], default='other', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('monthly_sale', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='app.monthlyclosing')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app.sale')),
            ],
            options={
                'verbose_name_plural': '5.3. Sale Retrn',
            },
        ),
        migrations.CreateModel(
            name='SaleRetrnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='app.saleretrn')),
            ],
            options={
                'verbose_name_plural': '5.4. Sale Return Items',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8.0 Stock Adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name_plural': '8.1. Stock Adjustment Items',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='app.purchaseitem')),
            ],
            options={
                'verbose_name_plural': '7.1 Batches',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional', max_digits=10, null=True)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sale')),
                ('batches_used', models.ManyToManyField(blank=True, related_name='sale_items', to='app.stockbatch')),
            ],
            options={
                'verbose_name_plural': '5.1. Sale Items',
            },
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField(help_text='Explain what the user should do in this step.')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='training_screenshots/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.trainingtopic')),
            ],
            options={
                'verbose_name_plural': '📗 Training Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='app.vendorgroup'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location')),
            ],
            options={
                'verbose_name_plural': '6. Warehouses',
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.warehouse'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app.warehouse'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField(default=0, editable=False)),
                ('reserved_stock', models.FloatField(default=0, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '7. Inventory',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='app.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '6.1. Warehouse Transfers',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'group'], name='app_custome_name_0603dd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='app_product_name_f168ea_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name', 'group'], name='app_vendor_name_460630_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='app_warehou_name_742b3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('product', 'warehouse', 'purchase_item')},
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor', 'pur_date'], name='app_purchas_vendor__9f62cf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['bill_no', 'warehouse'], name='app_purchas_bill_no_1228bc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'warehouse'], name='app_invento_product_185571_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse')},
        ),
    ]
