# Generated by Django 5.2.13 on 2026-08-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_debtpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebtPayment',
        ),
    ]
