# Generated by Django 5.2 on 2025-06-11 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_ref_contact_number_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=100)),
            ],
            options={
                'verbose_name_plural': '10.2 Savings',
            },
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name_plural': '10.1. Debts'},
        ),
    ]
