# Generated by Django 5.2.13 on 2026-08-01 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_debtpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('loan_agreement_no', models.CharField(max_length=50, verbose_name='Loan Agreement No')),
                ('lender_name', models.CharField(max_length=200, verbose_name='Lender/Bank Name')),
                ('return_type', models.CharField(choices=[('installment', '📅 Installment Payment'), ('full', '💰 Full Settlement'), ('partial', '📊 Partial Payment'), ('early', '⚡ Early Repayment')], default='installment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Return Amount')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', '💵 Cash'), ('bank_transfer', '🏦 Bank Transfer'), ('credit_card', '💳 Credit Card'), ('debit_card', '💳 Debit Card'), ('cheque', '📄 Cheque'), ('online', '🌐 Online Payment'), ('other', '📋 Other')], default='bank_transfer', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='loan_returns/')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('paid', '✅ Paid'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loan Returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('business', '🏢 Business Loan'), ('personal', '👤 Personal Loan'), ('vehicle', '🚗 Vehicle Loan'), ('property', '🏠 Property Loan'), ('education', '📚 Education Loan'), ('other', '📋 Other')], default='business', max_length=20)),
                ('lender_name', models.CharField(max_length=200, verbose_name='Lender/Bank Name')),
                ('lender_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement_no', models.CharField(blank=True, max_length=50, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate %', max_digits=5)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan_date', models.DateField(default=django.utils.timezone.now, verbose_name='Loan Received Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('total_installments', models.IntegerField(default=0)),
                ('paid_installments', models.IntegerField(default=0)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', '✅ Active'), ('paid', '💰 Paid'), ('defaulted', '❌ Defaulted'), ('cancelled', '❌ Cancelled')], default='active', max_length=20)),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose of Loan')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='loan_agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loans',
                'ordering': ['-loan_date'],
                'indexes': [models.Index(fields=['loan_no'], name='app_loan_loan_no_3a4cb2_idx'), models.Index(fields=['lender_name'], name='app_loan_lender__e72055_idx'), models.Index(fields=['status'], name='app_loan_status_39bfb5_idx')],
            },
        ),
    ]
