# Generated by Django 5.2.13 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_custom_barcode',
            field=models.BooleanField(default=False, help_text='Check this to manually enter supplier barcode instead of auto-generating', verbose_name='Use Custom/Supplier Barcode'),
        ),
    ]
