# Generated by Django 5.2.13 on 2026-08-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loanreturn_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
