# Generated by Django 5.2.13 on 2026-04-22 17:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_use_custom_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='Order Number')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready to Ship'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Order Notes')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Advance Payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_to_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_order', to='app.sale')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '5.0 Sale Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('reserved', models.BooleanField(default=False, help_text='Reserve this stock for the order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.saleorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name_plural': '5.0.1 Sale Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['order_no'], name='app_saleord_order_n_8c4576_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['customer'], name='app_saleord_custome_311ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['status'], name='app_saleord_status_a8c58d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleorderitem',
            unique_together={('order', 'product')},
        ),
    ]
