# Generated by Django 5.2.13 on 2026-08-03 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cashtransaction_balance_cashtransaction_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('personal', '👤 Personal Loan'), ('business', '🏢 Business Loan'), ('employee', '👔 Employee Loan'), ('customer', '🛒 Customer Loan'), ('friend', '🤝 Friend/Family Loan'), ('other', '📋 Other')], default='personal', max_length=20)),
                ('borrower_name', models.CharField(max_length=200, verbose_name='Borrower Name')),
                ('borrower_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('borrower_cnic', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNIC')),
                ('borrower_address', models.TextField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate %', max_digits=5)),
                ('total_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan_date', models.DateField(default=django.utils.timezone.now, verbose_name='Loan Given Date')),
                ('due_date', models.DateField(verbose_name='Expected Return Date')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('total_installments', models.IntegerField(default=0)),
                ('received_installments', models.IntegerField(default=0)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', '✅ Active'), ('paid', '💰 Paid'), ('defaulted', '❌ Defaulted'), ('cancelled', '❌ Cancelled')], default='active', max_length=20)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='loan_given_agreements/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loans Given',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanGivenPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.loangiven')),
            ],
        ),
        migrations.AddIndex(
            model_name='loangiven',
            index=models.Index(fields=['loan_no'], name='app_loangiv_loan_no_e720cf_idx'),
        ),
        migrations.AddIndex(
            model_name='loangiven',
            index=models.Index(fields=['borrower_name'], name='app_loangiv_borrowe_427a60_idx'),
        ),
        migrations.AddIndex(
            model_name='loangiven',
            index=models.Index(fields=['status'], name='app_loangiv_status_4598f7_idx'),
        ),
    ]
