# Generated by Django 5.2.13 on 2026-08-04 18:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_loangiven_loangivenpayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseretrnitem',
            options={},
        ),
        migrations.AlterField(
            model_name='purchaseretrnitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('999999.999'))]),
        ),
    ]
