# Generated by Django 5.2.13 on 2026-04-23 19:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_saleorder_saleorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=20, unique=True, verbose_name='Challan Number')),
                ('challan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Challan Date')),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('transfer', 'Stock Transfer'), ('job_work', 'Job Work'), ('approval', 'On Approval'), ('return', 'Return to Vendor'), ('other', 'Other')], default='sale', max_length=20, verbose_name='Reason for Dispatch')),
                ('vehicle_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vehicle Number')),
                ('transport_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transport Company')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name')),
                ('driver_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Driver Contact')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_sale', models.BooleanField(default=False, verbose_name='Converted to Invoice')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Customer/Receiver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='app.saleorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '5.2 Delivery Challans',
                'ordering': ['-challan_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Price (Optional)')),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Remarks')),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.deliverychallan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan_items', to='app.saleitem')),
            ],
            options={
                'verbose_name_plural': '5.2.1 Delivery Challan Items',
            },
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['challan_no'], name='app_deliver_challan_6c8f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['customer'], name='app_deliver_custome_b1afd2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['order'], name='app_deliver_order_i_b6cbb1_idx'),
        ),
    ]
