# Generated by Django 5.2.13 on 2026-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_deliverychallan_deliverychallanitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='order_qty',
            field=models.FloatField(default=0, verbose_name='Order Qty'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='pending_qty',
            field=models.FloatField(default=0, verbose_name='Pending Qty'),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='qty',
            field=models.FloatField(verbose_name='Delivery Qty'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready to Ship'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
