# Generated by Django 5.2.13 on 2026-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_purchaseretrnitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseretrnitem',
            options={'verbose_name_plural': '4.4. Purchase Return Items'},
        ),
        migrations.AlterField(
            model_name='purchaseretrnitem',
            name='qty',
            field=models.FloatField(),
        ),
    ]
