# Generated by Django 5.2.13 on 2026-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_purchaseretrnitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseretrnitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
