# Generated by Django 5.2.13 on 2026-04-24 19:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_deliverychallanitem_order_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=20, unique=True, verbose_name='GRN Number')),
                ('grn_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received Date')),
                ('reason', models.CharField(choices=[('purchase', 'Purchase Order'), ('direct', 'Direct Purchase'), ('return', 'Customer Return'), ('other', 'Other')], default='purchase', max_length=20, verbose_name='Reason')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Invoice No')),
                ('vehicle_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vehicle Number')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_purchase', models.BooleanField(default=False, verbose_name='Converted to Purchase')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor', verbose_name='Vendor/Supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '4.2 Goods Received Notes',
                'ordering': ['-grn_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.FloatField(default=0, verbose_name='Order Qty')),
                ('qty', models.FloatField(verbose_name='Received Qty')),
                ('pending_qty', models.FloatField(default=0, verbose_name='Pending Qty')),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.goodsreceivednote')),
            ],
            options={
                'verbose_name_plural': '4.2.1 Goods Received Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Order Notes')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Advance Payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_to_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_order', to='app.purchase')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app.vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '4.0 Purchase Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='app.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name_plural': '4.0.1 Purchase Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_no'], name='app_purchas_order_n_89c7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='app_purchas_vendor__69ee5e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='app_purchas_status_c8a7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['grn_no'], name='app_goodsre_grn_no_1a8ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['vendor'], name='app_goodsre_vendor__f4b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['purchase_order'], name='app_goodsre_purchas_623a79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('order', 'product')},
        ),
    ]
