# Generated by Django 5.2.13 on 2026-04-24 20:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_goodsreceivednote_goodsreceiveditem_purchaseorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_no', models.CharField(max_length=20, unique=True, verbose_name='Audit Number')),
                ('audit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Audit Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Audit Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
            options={
                'verbose_name_plural': '7.2 Stock Audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.FloatField(default=0, verbose_name='System Stock')),
                ('physical_qty', models.FloatField(blank=True, null=True, verbose_name='Physical Count')),
                ('variance', models.FloatField(default=0, verbose_name='Variance (+/-)')),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('adjusted', models.BooleanField(default=False, verbose_name='Stock Adjusted')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.stockaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name_plural': '7.2.1 Stock Audit Items',
            },
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['audit_no'], name='app_stockau_audit_n_fbf45d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['warehouse'], name='app_stockau_warehou_b92033_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['status'], name='app_stockau_status_4988af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockaudititem',
            unique_together={('audit', 'product')},
        ),
    ]
