# Generated by Django 5.2.13 on 2026-08-17 06:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_purchaseretrnitem_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseretrn',
            options={'ordering': ['-purchase_return_date'], 'verbose_name_plural': '4.4. Purchase Returns'},
        ),
        migrations.AddField(
            model_name='purchaseretrn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 17, 11, 53, 43, 27725)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseretrn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseretrn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseretrn',
            name='bill_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseretrn',
            name='return_reason',
            field=models.CharField(choices=[('damaged', 'Damaged Goods'), ('incorrect', 'Incorrect Shipment'), ('expired', 'Expired Stock'), ('quality', 'Quality Issue'), ('wrong_item', 'Wrong Item Received'), ('excess', 'Excess Quantity'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AddIndex(
            model_name='purchaseretrn',
            index=models.Index(fields=['purchase', 'vendor'], name='app_purchas_purchas_8c67c6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseretrn',
            index=models.Index(fields=['purchase_return_date'], name='app_purchas_purchas_5fa623_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseretrn',
            index=models.Index(fields=['return_reason'], name='app_purchas_return__71ebd7_idx'),
        ),
    ]
