# Generated by Django 5.2.13 on 2026-08-17 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_purchaseretrn_options_purchaseretrn_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseretrn',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
