# Generated by Django 5.2.13 on 2026-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_purchaseretrn_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleretrnitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
