# Generated by Django 5.2.13 on 2026-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_saleretrnitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleretrn',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
