name: Django CI & Database Migration

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pymysql mysqlclient django-dbbackup django-import-export django-axes reportlab
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Check Database Connection & Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Django Checks
      run: |
        python manage.py check
